sdk: "/Library//Ruby/Gems/1.8/gems/rhodes-2.3.1"
sdkversion: 2.3.0
name: imBored-native
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.imBored-native
  BundleURLScheme: imBored-native

extensions: ["json", "another-extension", "net-http", "debugger"]
